project:
  type: website
  output-dir: docs

from: markdown+emoji

website:
  title: "&lt;seh&gt;"
  navbar:
    search: true
    left:
      - file: index.qmd
        text: Home
      - file: education.qmd
        text: "Education"
      - sidebar:scholarship
      - sidebar:teaching

  sidebar: 
    - title: "Education"
      style: "docked"
      background: "light"
      contents: 
        - education.qmd
    
    - id: scholarship
      title: "Scholarship"
      contents:
        - scholarship.qmd
        - projects.qmd
  
    - id: teaching
      title: "Teaching"
      contents:
        - teaching.qmd
        - teachingphilosophy.qmd
  
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

