---
title: "Metaresearch"
editor: visual
---

#### Overview

Meta-research is the study of various aspects of research itself, including the types of methods used, reporting of research results, and evaluation of research impact.  This area is a relatively new focus for me and is largely a result of my involvement in the scholarly publishing enterprise. After attending presentations on topics related to research on the peer-review process and research dissemination and reflecting on my own experience as an editor, I have begun to consider the potential for meta-research in both pharmacy and health professions education scholarship. Below are a few examples of scholarship efforts I have in this area.<br><br>

#### Lines of Inquiry

* *Open science practices in the health professions* <br>
There has been an expanding body of work examining open science attitudes and practices among researchers in various fields. The health professions have not been a focus of this existing work. There is an understandable tension between the movement to make science more openly available and the perceived need for biomedical research to be somewhat closed and protected from the perspective of protecting patients from undue harm resulting from the use of therapies described in papers that have yet to be peer reviewed. I recently finished collecting data on open science practices and attitudes among pharmacy faculty in the US and analysis is beginning. My goal is to expand on this work by including a broader range of health professions and to examine open science practices in health professions education scholars. 

* *Reviewing and publishing patterns*<br>
Peer review is a cornerstone of the current scientific publishing process. Over the course of the COVID-19 pandemic, many journals experienced an increase in the number of submissions without a subsequent increase in the number of reviewers. If anything, reviewers were sometimes harder to find, especially for journals seeking reviews from current practitioners. Anecdotally, pharmacy seems to have drawn from a similar pool of reviewers. This is no doubt similar in other health professions. For this project, I have obtained the reviewers for 12 pharmacy journals and will be conducting network analysis to examine how closely related the journals are through their reviewers. A similar issue is individuals who submit papers to journals for review but do not serve as reviewers themselves. As an editor, I have access to the reviewers and submitters. I am currently in the process of obtaining approval from different pharmacy journals to obtain data to compare patterns of reviewers and submitters. Assuming I can get other pharmacy journals to join, this could be the starting point of future scholarly efforts in pharmacy publishing by connecting the different journals. Ideally, I would like to expand these projects to other health professions

* *Registration of studies of pharmacy care services*<br>
Registration of studies can promote research transparency and accountability. Federal law requires registration and reporting of results from FDA-regulated trials and federally sponsored research in study registries, such as ClinicalTrials.gov. Registration of trials prior to subject enrollment has been required by the International Committee of Medical Journal Editors since 2005. I have published an initial study in this area examining the prevalence and type of studies of pharmacy care services found in ClinicalTrials.gov.  The next steps in this area involve describing the prevalence of pre-registered studies in pharmacy journals and examining why these studies are not registered.

* *Quality of survey research*<br>
Survey methods are not an uncommon research approach, especially in pharmacy research. One common concern in survey research is response rates, which have been shown to be on the decline. A historical review of survey-based research published in pharmacy journals between 1988 and 2018 was conducted to examine the types of survey methods used, application of best practices, reported response rate, and characteristics of groups being surveyed. Preliminary analysis of 2018 data were presented at the American Pharmacists Association 2022 Annual Meeting.  Additional data collection is planned to include studies published in 2023 and then analysis across all years will be conducted to examine predictors of response rates. 

