---
title: "Scholarship Overview"
editor: visual
---

#### Overview

My scholarly efforts have focused on three primary areas: educational scholarship, meta-research, and medication use research. The relative effort I have devoted to each has changed over the course of my career. Based on my professional and graduate training in pharmacy, I was primarily focused on medication use research in the early stages of my career. Given the relatively high teaching load I had as a junior faculty member, I took advantage of several professional development opportunities related to the scholarship of teaching and learning. This sparked my interest in the area of educational scholarship. By the time I reached my initial promotion to associate professor in 2010, I had already begun to devote a notable portion of my scholarship efforts to education-related topics. Interestingly, the foundation research methods classes I took in graduate school were educational research classes. On some level, I suppose that was some unexpected foreshadowing related to my research trajectory. My commitment to educational scholarship grew and became more focused as I assumed leadership roles in curriculum development and assessment. Those expanded roles and the connections I made with faculty teaching in other areas (e.g., education, engineering, medicine, public health) spurred me to begin taking a broader look at education in professional programs. This broad perspective has helped me incorporate theories, viewpoints, and methods that are not commonly used in pharmacy education, and sometimes health professions education. As I began looking at work across professional education programs, I developed an interest in questions related to the research process itself. It was several years before I realized that type of work had a name: meta-research. My interest in meta-research strengthened with my appointment to editorial positions where I saw a very different side of the scholarship process. Currently, my scholarship efforts are primarily focused on educational scholarship and meta-research. I do maintain a certain level of activity in medication use research, but this is primarily through collaborative efforts with other researchers or through mentoring trainees. Although three distinct areas, there is overlap and substantial interaction between my areas of scholarship.


#### Approach to scholarship

From a research methods standpoint, I typically draw on approaches from the epidemiological or sociobehavioral
traditions. I also have a strong background in quantitative statistical methods. Given my focus on methods and analysis, I am often asked to join research projects as a collaborator bringing expertise in methods and analysis.
Collaboration is important to me as a researcher because it promotes diversity in thought and method. This can produce stronger studies and maintain a high level of applicability to education and practice. I think it is important to consider why a particular research approach is being used and whether that is the most appropriate keeping in mind that there may be options worth considering that are more commonly used outside the health professions (e.g., education, social work, business). When I collaborate with others, this is the perspective I try to bring to the research endeavor. Although I am not currently a practicing pharmacist, I have been able to draw on my clinical training and previous practice experience to work effectively with faculty who are primarily practice-focused by bridging the gap between some of the seemingly esoteric, but very important, issues associated with conducting research and the practical relevance of the project at hand. Ensuring applicability to education and practice has always been an important consideration in my scholarship efforts. In fact, I think that certain types of educational scholarship can be viewed as a form of practice-based research. The motivation for many of my projects are frequently rooted in my experiences as an educator, a researcher, and even my service as an editor. This allows me to keep the practical application front and center when designing projects.
