---
title: "Teaching Philosophy"
editor: visual
---

Drawing on my own experiences as a learner and an educator, I
view learning as the process of constructing knowledge with the ultimate goal
of personal growth and transformation. Understandably, this transformation may not
be realized within our immediate spheres of influence as educators. We still hope
that what students learn from our respective classes or training programs will
help them in their own personal and professional journeys. As a transformative
process, learning requires more than the mere acquisition of facts. Those facts
must be assembled and be ready for use in practice. This view of learning as
growth and transformation has a few important implications for how I approach my
practice as an educator.

-   Learning is an active process

-   Learning require vulnerability and can be uncomfortable

-   Learning involves individual ownership

-   Learning is a bidirectional, mutual process

-   Learning requires support

-   Learning is situated within various systems

-   Learning is about making connections

-   Learning is a continuous process that never stops
